apiVersion: apps/v1
kind: Deployment
metadata:
  name: notesapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notesapi
  template:
    metadata:
      labels:
        app: notesapi
    spec:
      containers:
      - name: notesapi-container
        image: piyush1127/spring-boot-docker:latest
        ports:
        - containerPort: 9099