apiVersion: v1
kind: Service
metadata:
  name: notesapi-service
spec:
  selector:
    app: notesapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9099
  type: LoadBalancer  # Or LoadBalancer if you're on a cloud provider